name: ruff
on:
  push:
    branches: [ main ]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python with uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        python-version: ${{ matrix.python-version }}

    - name: Lint with ruff
      uses: astral-sh/ruff-action@v3

